name: Run R Exit Velos Script

on:
  schedule:
    - cron: '0 18 * * *'  # Every day at 18:00 UTC
  workflow_dispatch:

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'  # Use a recent R version

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libcurl4-openssl-dev libssl-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("baseballr", "dplyr", "xml2", "httr", "janitor"), repos = "https://cloud.r-project.org", dependencies = TRUE, verbose = TRUE)'

      - name: Verify script
        run: ls -l test_script.R

      - name: Run R script
        run: Rscript test_script.R
